### ISSUE TITLE
Modal does not provide backdrop w/ bootstrap 3.3.2

### ISSUE THREAD

**Issue by newmanw** [angular-ui/bootstrap#3378]
Looks like bootstrap 3.3.2 does not have the bottom 0 anymore on modal-backdrop class

```css
.modal-backdrop {
  bottom: 0;
}
```

This means that the modal dialog does not calc the correct height for the backdrop fade.

plunker here:
http://plnkr.co/edit/5vPyWJvl1Xzs4bYAAebC?p=preview
