### ISSUE TITLE
Modal's backdrop mechanism not working when overriding windowTemplate.html

### ISSUE THREAD

**Issue by heditr** [angular-ui/bootstrap#4878]
I'm working on the modal component, i did override template/modal/window.html to adapt some CSS from a specific mock-up.
```javascript
$scope.openRefuseModal = function($event) {
      $uibModal.open({
        animation : true,
        templateUrl : 'modalRefuse.html',
        windowTemplateUrl : 'windowTemplate.html',
        controller : 'ModalCtrl',
        backdrop: true
      }).rendered.then(function() {
        var mod = angular.element(document.querySelector('#' +
          $event.target.id));
        var mod2 = angular.element(document.querySelector('#modal'));
        mod.parent().append(mod2);
      });
    };
```
This is my mockup modal content: 
```html
<script type="text/ng-template" id="modalRefuse.html">
  <ul id="tooltip-refuse-1" style="display: block;">
    <li><a href="" rel="popup-refuse" class="poplight" ng-click="openRefuse()">{{ "sign.refuse.definitively" | translate }}</a></li>
    <li><a href="">{{ "sign.leave" | translate }}</a></li>
    <li><a href="" class="cancel-refuse" ng-click="cancel()">{{ "sign.cancel" | translate }}</a></li>
  </ul>
</script>
```
And the window template for overriding the custom one.
```html
<script type="text/ng-template" id="windowTemplate.html">
    <div id="modal" class="div-refuse center" modal-render="{{$isRendered}}" role="dialog"
      uib-modal-animation-class="fade" modal-in-class="in">
      <div uib-modal-transclude style="position: static;"></div>
    </div>
</script>
```
And the index.html for opening the modal.

```html
<div class="to-append">
        <a href="" id="refuse-1" class="refuse" ng-click="openRefuseModal($event)">{{ "sign.refuse" | translate }}</a>
</div>
```

```css
/***** Refuse div *****/
.div-refuse li:hover a{
	opacity:.8;
}
#to-sign .div-refuse{
  position: relative;
	width:350px;
	margin:-15px auto;
  height: 32px;
  padding: 8px 12px 8px 8px;
  vertical-align: baseline;
	z-index:88888;
}
.div-refuse ul{
  position: absolute;
  bottom: 100%;
  left: 0;
  right: 0;
  background: #fff;
	list-style: none;
  border:1px solid #0072b2;
  border-radius: 5px;
  padding-left: 0;
  text-align: center;
  -webkit-transition: 0.2s ease-out;
  -moz-transition: 0.2s ease-out;
  -o-transition: 0.2s ease-out;
  transition: 0.2s ease-out;
  -webkit-transition-property: opacity, padding, visibility;
  -moz-transition-property: opacity, padding, visibility;
  -o-transition-property: opacity, padding, visibility;
  transition-property: opacity, padding, visibility;
  -webkit-box-shadow: inset 0 0 0 1px rgba(255, 255, 255, 0.9), 0 1px 2px rgba(0, 0, 0, 0.1);
  box-shadow:0 0 5px #0072b2;
}
.div-refuse ul:before, .div-refuse ul:after, .div-refuse li:first-child:after{
  content: '';
  display: block;
  position: absolute;
  left:49%;
  width: 0;
  height: 0;
  border: 7px outset transparent;
}
.div-refuse ul:before{
  bottom: -14px;
  border-top: 7px solid #0072b2;
}
.div-refuse li:first-child:after{
  bottom: -13px;
  border-top: 7px solid white;
}
.div-refuse ul:after{
  bottom: -12px;
  border-top: 7px solid #fff;
}
.div-refuse li{
  padding: 0 12px;
  font-size: 11px;
  color: #838ca2;
  text-shadow: 0 1px white;
}
.div-refuse li.sep{
  margin-top: 4px;
  padding-top: 4px;
  border-top: 1px solid #b4bbce;
  -webkit-box-shadow: inset 0 1px rgba(255, 255, 255, 0.6);
  box-shadow: inset 0 1px rgba(255, 255, 255, 0.6);
}
.div-refuse li a{
  display:inline-block;
	color:#0072b2;
	padding:15px;
	text-decoration:none;
	font-size:14px;
	border-bottom:1px solid #ddd;
}

.div-refuse li:first-child a{
	color:#a94442;
	font-weight:400;
}
.div-refuse li:last-child a{
	border-bottom:none;
}
.div-refuse li a:hover:after {
  display: block;
}
.div-refuse li a:after {
  content: '';
  display: none;
  position: absolute;
  top: 50%;
  right: 5px;
  margin-top: -4px;
  width: 0;
  height: 0;
  border: 4px solid transparent;
  border-left-color: #9facd1;
  border-left-color: rgba(255, 255, 255, 0.4);
}

@media screen and (max-width: 410px) {
  #to-sign .div-refuse {
    width:100%;
  }
}
```

The problem is when i open the modal and i want to use the backdrop mechanism(by clicking  outside the window popup) to close the window, it dosen't work. 
But when i click on the div#modal, it work normally(this div doesn't have the same width and height as the body).
I want to find a way to override the window popup and preserve the backdrop mechanism.
