### ISSUE TITLE
ng-cloak doesn't work for elements with the classes `collapse.navbar-collapse` 

### ISSUE THREAD

**Issue by ChristopherBrix** [angular-ui/bootstrap#4940]
As demonstrated in [this punker](http://run.plnkr.co/plunks/4t7Blve3N4gy1aFAPnm4/), the directive `ng-cloak` doesn't work if it's used on elements that have the two classes `collapse` and `navbar-collapse`.

This is a result of the rule `display: block !important;` for `.navbar-collapse.collapse` (this should be in line 4250 of the current complete bootstrap.css file) and could be fixed by adding 

```css
@media (min-width: 768px) {
  .navbar-collapse.collapse
      :not([ng\:cloak])
      :not([ng-cloak])
      :not([data-ng-cloak])
      :not([x-ng-cloak])
      :not(.ng-cloak)
      :not(.x-ng-cloak) {
    display: block !important;
  }
  
  .navbar-collapse.collapse[ng\:cloak],
  .navbar-collapse.collapse[ng-cloak],
  .navbar-collapse.collapse[data-ng-cloak],
  .navbar-collapse.collapse[x-ng-cloak],
  .navbar-collapse.collapse.ng-cloak,
  .navbar-collapse.collapse.x-ng-cloak {
    display: none !important;
  }
}
```

to the styles, as demonstrated in http://run.plnkr.co/plunks/RYRqZXmpjRuH9ycen9QI/

If you tell me where I should add this, I'm willing to implement the change and create a pull request.
